name: tyrant-unleashed-optimizer
version: daily
summary: Tyrant Unleashed Optimizer
description: |
  Simulator app for the game Tarant Unleashed that can be used to optimize your
  card deck for certain raids, or temporary buffs as well as growth planning in
  general.
confinement: strict

apps:
  sim:
    command: usr/local/bin/tuo.exe
    plugs: [home]
  updatexml:
    command: usr/local/bin/update_xml.sh
    plugs: [home, network]

parts:
  tyrant-unleashed-optimizer:
    # as we are part of the tuo git tree then just build locally
    source: .
    plugin: make
    build-packages:
      - g++
      - make
      - build-essential
      - libboost1.58-dev
      - libboost-system1.58-dev
      - libboost-thread1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-regex1.58-dev
    stage-packages:
      - curl
